### ISSUE TITLE
Roadmap 0.x

### ISSUE THREAD

**Issue by wizard-a** [9-web/zet-component#30]
## 0.x
-----------
### 框架
- [ ] 更新底层框架，从`umi-plugin-libray` 迁移到 `umi-library` #32 
- [ ] css Modules 规范约定 #45 
- [ ] tslint 静态代码检查 commit 规范，change log, 工程化的东西
- [ ] 支持单元测试
- [ ] 新增组件
- [ ] 优化和迁移组件 #13 
- [ ] 打包优化 （style，js 分离， 按需加载 `umi-library` 好像已支持）
- [ ] less 命名规范，常用布局整理 #45
- [ ] 组件数据 Mock

### 构建
- [ ] deploy 自动化 
- [ ] 私有npm仓库搭建，迁移gitlab
- [ ] 包安装时动态切换私有仓库和公开仓库 （可能需要开发一个安装包工具）

### 优化
- [ ] 现有的组件 review，文档案例补全 #31 
- [ ] less 样式 review
